# -*- mode: ruby -*-
# vi: set ft=ruby -*-
#
# Vagrant multi-machine configuration for building the OpenNTPD 7.9p1 oracle
# across all supported BSD operating systems.
#
# Usage:
#   cd research/vagrant
#   vagrant up                    # starts all boxes
#   vagrant up openbsd            # start only OpenBSD
#   vagrant up netbsd             # start only NetBSD
#   vagrant up freebsd            # start only FreeBSD
#   vagrant ssh openbsd           # SSH into OpenBSD
#   vagrant destroy -f            # tear down all boxes
#
# Provisioning builds ntpd from source and places it at the platform's
# standard sbin path. See per-box Vagrantfiles under this directory for
# the exact provisioning scripts.

Vagrant.configure("2") do |config|
  config.vm.define "openbsd" do |box|
    box.vm.box = "generic/openbsd7"
    box.vm.hostname = "openntpd-oracle"
    box.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 2
    end
    box.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
    box.vm.synced_folder ".", "/vagrant", disabled: true
    box.vm.provision "shell", inline: <<-SHELL
      pkg_add ca-certificates
      cd /tmp
      ftp https://ftp.openbsd.org/pub/OpenBSD/OpenNTPD/openntpd-7.9p1.tar.gz
      echo "091eeb3f4e358e28c3ab2ea58f93d7a0b5758a20d7c8a0418e162e9b2c27addc  openntpd-7.9p1.tar.gz" > openntpd-7.9p1.tar.gz.sha256
      sha256 -C openntpd-7.9p1.tar.gz.sha256 openntpd-7.9p1.tar.gz
      tar xzf openntpd-7.9p1.tar.gz
      cd /tmp/openntpd-7.9p1
      ./configure
      make
      make install
      strip /usr/local/sbin/ntpd
      echo "OpenBSD oracle build complete"
    SHELL
  end

  config.vm.define "netbsd" do |box|
    box.vm.box = "generic/netbsd10"
    box.vm.hostname = "openntpd-oracle"
    box.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 2
    end
    box.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
    box.vm.synced_folder ".", "/vagrant", disabled: true
    box.vm.provision "shell", inline: <<-SHELL
      pkgin update
      pkgin -y install ca-certificates libtls gmake
      cd /tmp
      ftp https://ftp.openbsd.org/pub/OpenBSD/OpenNTPD/openntpd-7.9p1.tar.gz
      echo "091eeb3f4e358e28c3ab2ea58f93d7a0b5758a20d7c8a0418e162e9b2c27addc  openntpd-7.9p1.tar.gz" > openntpd-7.9p1.tar.gz.sha256
      cksum -a sha256 openntpd-7.9p1.tar.gz | cmp - openntpd-7.9p1.tar.gz.sha256
      tar xzf openntpd-7.9p1.tar.gz
      cd /tmp/openntpd-7.9p1
      ./configure
      gmake
      gmake install
      strip /usr/pkg/sbin/ntpd
      echo "NetBSD oracle build complete"
    SHELL
  end

  config.vm.define "freebsd" do |box|
    box.vm.box = "generic/freebsd14"
    box.vm.hostname = "openntpd-oracle"
    box.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 2
    end
    box.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end
    box.vm.synced_folder ".", "/vagrant", disabled: true
    box.vm.provision "shell", inline: <<-SHELL
      pkg update
      pkg install -y ca_root_nss gcc bison flex wget
      cd /tmp
      wget https://ftp.openbsd.org/pub/OpenBSD/OpenNTPD/openntpd-7.9p1.tar.gz
      echo "091eeb3f4e358e28c3ab2ea58f93d7a0b5758a20d7c8a0418e162e9b2c27addc  openntpd-7.9p1.tar.gz" > openntpd-7.9p1.tar.gz.sha256
      sha256 -c openntpd-7.9p1.tar.gz.sha256
      tar xzf openntpd-7.9p1.tar.gz
      cd /tmp/openntpd-7.9p1
      ./configure
      make
      make install
      strip /usr/local/sbin/ntpd
      echo "FreeBSD oracle build complete"
    SHELL
  end
end
