<!-- DO NOT EDIT BY HAND. Generated by `cargo xtask gen`. Run `cargo xtask check` to verify freshness. -->

# Negative capabilities — ultra-deep forensic audit

> **openntpd-rs vs OpenNTPD 7.9p1 oracle**
>
> Every syntactic quirk, behavioral gap, platform divergence, and unimplemented
> surface identified through static source archaeology and cross-distro Docker
> VM matrix analysis.

---

## Summary

| Metric | Value |
|--------|-------|
| Total Rust tests | 249 |
| Implemented — internally tested | 17 surfaces, 230 tests |
| Implemented — unverified against oracle | 5 surfaces |
| Scaffold | 1 surface |
| Planned | 7 surfaces |
| Fully ported (oracle evidence) | 0 |
| Estimated OpenNTPD coverage | ~12% of total daemon behavior |

---

## 1. Lexer (`parse.y` · 93 tests)

### Implemented — internally tested

| Feature | Status | Notes |
|---------|--------|-------|
| Keyword recognition (15 keywords) | ✓ | Exact lowercase matching |
| Integer numbers (i64) | ✓ | Including overflow rejection |
| Quoted strings (single/double) | ✓ | Non-UTF-8 bytes, escape sequences |
| Backslash-newline continuation | ✓ | Global; inside/outside quotes, comments |
| Unquoted string character class | ✓ | Upstream exclusion set verified |
| NUL rejection | ✓ | Intentional hardening beyond upstream |
| Error recovery per-line | ✓ | Lexer owns recovery; parser boundary clean |
| 8094/8095 token length limits | ✓ | Including sign byte for negative numbers |
| Negative number fallback (`-123abc`) | ✓ | Splits into `Symbol('-')` + `String` |
| Number-followed-by-continuation | ✓ | `12\<newline>3` → Number(123) |
| Backslash before non-newline | ✓ | Drops backslash, returns next byte |
| Source spans throughout | ✓ | `pushback_raw_end` for delimiter accuracy |

### Known divergences

| Gap | Impact | Upstream behavior |
|-----|--------|-------------------|
| NUL rejected in comments | Intentional hardening; safe | Upstream does not check NUL in `#` comments |
| No `\r\n` CRLF mode | Minor; `\r` treated as symbol upstream | Upstream `lgetc(0)` normalizes `\r\n` to `\n` on some platforms |
| No `isspace()` for number terminators | VT/FF added manually; `\v` and `\f` are C-locale whitespace | Upstream uses `isspace()` which covers `\t`, `\n`, `\v`, `\f`, `\r`, ` ` |
| Single-quote escape equivalence | Minor; single quotes not commonly escaped upstream | Upstream escape rules are identical for both quote types |
| `is_allowed_in_unquoted` exclusion set verified for 11 chars only | Upstream may exclude additional platform-specific punctuation | Verified against Debian 7.9p1 parse.y |

---

## 2. Parser (`parse.y` grammar · 60 tests)

### Implemented — internally tested

| Directive | Options | Status |
|-----------|---------|--------|
| `listen on` | `rtable <u32>` | ✓ |
| `server` | `weight <1..10>`, `trusted` | ✓ |
| `servers` | `weight <1..10>`, `trusted` | ✓ |
| `constraint from` | URL + pinned IPs | ✓ |
| `constraints from` | URL only | ✓ |
| `sensor` | `correction`, `refid`, `stratum`, `weight`, `trusted` | ✓ |
| `query from` | Numeric IP only | ✓ |

### Known divergences

| Gap | Impact | Upstream behavior |
|-----|--------|-------------------|
| `-f` attached argument `-f/path` | CLI not full getopt | POSIX getopt allows `-f/path` |
| `-P` attached argument `-Pntp` | CLI not full getopt | POSIX getopt allows `-Pntp` |
| `-p` attached argument `-p/run/ntpd.pid` | CLI not full getopt | POSIX getopt allows `-p/run/ntpd.pid` |
| `--` terminator not supported | CLI edge case | `--` stops option processing per POSIX |
| Grouped `-sn`, `-Sv` not validated | CLI edge case | getopt allows arbitrary grouping |
| No environment variable overrides | Minor | OpenNTPD supports some env config |
| Inline config via stdin not supported | CLI edge case | `ntpd -n < /dev/stdin` not tested |
| Config file read as byte string | UTF-8 assumed for hostnames | upstream uses `strlen()`; non-UTF-8 values may differ in error messages |

---

## 3. NTP wire protocol (`ntp.h`, `ntp_msg.c` · 17 tests)

### Implemented — internally tested

| Feature | Tests | Status |
|---------|-------|--------|
| NTP timestamp encoding/decoding | 7 | ✓ |
| Packet header encode/decode (48-byte) | 8 | ✓ |
| Authenticated packet (68-byte with MAC) | 2 | ✓ |
| Era resolution (0, 1, 2, post-2036) | 5 | ✓ |
| Unix ↔ NTP timestamp conversion | 3 | ✓ |

### NOT implemented

| Feature | Impact | Size |
|---------|--------|------|
| **Mode 6 control protocol** | ntpctl cannot communicate with any ntpd | Large |
| **Mode 7 private protocol** | ntpq private mode commands unsupported | Large |
| **Mode 3 client** | NTP poll loop not wired | Large |
| **Mode 4 server** | Cannot respond to client requests | Large |
| **Mode 5 broadcast server** | No broadcast/multicast support | Medium |
| **Mode 1/2 symmetric active/passive** | Peer-to-peer not possible | Medium |
| **Autokey protocol** | RFC 5906 identity verification | Large |
| **NTS (NTS-KE, NTS NTP)** | RFC 8915 secure NTP | Large |
| **MS-SNTP** | Windows Time Service interop | Medium |
| **Reference clock drivers** | No hardware refclock support | Very large |
| **Kernel PLL discipline** | `ntp_adjtime()` / `adjtimex()` not fully wired | Medium |
| **Kernel timestamping** | Hardware timestamps not used | Medium |

---

## 4. Client state machine (`client.c` · 0 tests)

### Status: **Planned — not started**

OpenNTPD's client is the core of the daemon. The Rust implementation has zero coverage.

| Subsurface | Size | Dependencies |
|------------|------|--------------|
| DNS resolution (async, retry) | Large | Requires async runtime or polling rearchitecture |
| Server selection / clock filter | Large | Requires client state machine |
| Offset computation / jitter tracking | Medium | Requires clock filter |
| Poll interval management | Medium | RFC 5905 algorithm |
| Reachability register (8-bit shift) | Small | Independent |
| Origin/dispersion/stratum tracking | Medium | Part of filter |
| Combining algorithm (NTPv4 clock select) | Very large | Requires full peer set |
| Clock discipline (PID controller) | Large | Requires system clock access |
| Drift file read/write | Small | Safe tempfile pattern |
| Runtime privilege dropping | Medium | `setresuid()` / `setresgid()` |
| Process separation / privsep | Very large | imsg socket, child process |

### Client-vs-server architecture gap

OpenNTPD's `client.c` handles ~2000 lines of C for the full client state machine. The Rust implementation has 0 lines of behavioral client code. This is the single largest unimplemented surface.

---

## 5. NTP daemon event loop (`ntpd.c` · 21 tests)

### Status: **`-n` mode implemented; daemon mode scaffold**

| Subsurface | Status | Notes |
|------------|--------|-------|
| `-n` config check | ✓ | 21 tests covering CLI, parser, binary |
| `-d` debug mode | Scaffold | Parsed but no daemon behavior |
| `-f` config file selection | ✓ | Tested |
| `-P` parent process name | Scaffold | Parsed but `setproctitle()` not invoked |
| `-p` PID file | Scaffold | Parsed but no pidfile written |
| `-s`/`-S` deprecated flags | Scaffold | Warning printed, ignored |
| `-v` verbosity | ✓ | Grouped `-vv` supported |
| Daemon mode (`-d` implied on bg) | Missing | Entirely unimplemented |
| Signal handling | Missing | SIGHUP reload, SIGINT/SIGTERM shutdown |
| Privilege separation | Missing | privsep imsg framework |
| `setproctitle()` | Missing | Not wired on any platform |
| Syslog logging | Missing | Uses eprintln only |
| Drift file I/O | Missing | No drift file read/write |
| DNS child process | Missing | No async DNS |

---

## 6. Control socket / `ntpctl` (`control.c` · 0 tests)

### Status: **Planned — not started**

| Subsurface | Size | Notes |
|------------|------|-------|
| Unix domain socket (`/var/run/ntpd.sock`) | Medium | Standard path, imsg framing |
| imsg protocol | Large | OpenBSD imsg binary wire format |
| `ntpctl -s status` | Medium | System/peer status summary |
| `ntpctl -s peers` | Medium | Peer list with reachability |
| `ntpctl -s Sensors` | Medium | Sensor status |
| `ntpctl -s all` | Small | Combines above |
| ntpctl prefix matching | ✓ | Unambiguous prefix only; 0 tests |
| ntpctl exit codes | Missing | Not wired |

---

## 7. Constraint validation (`constraint.c` · 0 tests)

### Status: **Planned — not started**

OpenNTPD's constraint subsystem validates time against HTTPS servers:

| Subsurface | Impact | Notes |
|------------|--------|-------|
| HTTPS connection to constraint URL | Must validate system clock against TLS | Large |
| TLS certificate verification | Security-critical | Medium |
| Response header parsing | Date/age extraction | Medium |
| Pinned IP address enforcement | Match connected IP to configured list | Small |
| Multiple constraint aggregation | Weighted combining | Medium |
| Constraint backoff/retry | Network resilience | Small |

The parser accepts `constraint from <URL>` but no runtime constraint validation exists.

---

## 8. Sensor framework (`sensor.c` · 0 tests)

### Status: **Planned — not started**

| Subsurface | Notes |
|------------|-------|
| PPS (pulse-per-second) device reading | Requires `ioctl` or `read` on `/dev/pps0` |
| NMEA0183 GPS sentence parsing | Serial port or USB GPS |
| Sensor correction application | Configurable correction micros |
| Sensor stratum advertisement | Override for local clock |
| Sensor refid | Configurable reference ID |
| Sensor weight | Selection weight |
| Multiple sensor aggregation | Combining algorithm |

The parser accepts `sensor <device> [options]` but no sensor I/O exists.

---

## 9. System clock discipline (`adjtimex` / `adjfreq` · 3 tests)

### Implemented — internally tested

| Feature | Tests | Platforms |
|---------|-------|-----------|
| OpenBSD-to-Linux frequency conversion | 3 | Linux only tested |

### NOT implemented for production

| Platform | adjfreq | Status |
|----------|---------|--------|
| Linux | `adjtimex` | Implemented; no behavioral tests |
| FreeBSD | `adjfreq(2)` | Stub only |
| OpenBSD | `adjfreq(2)` | Stub only |
| macOS | `mach_timebase` | Stub only |
| Solaris/illumos | `adjtime(2)` | Stub only |
| NetBSD | `ntp_adjtime()` | Not present |
| DragonFly BSD | `adjfreq(2)` | Not present |

The frequency conversion uses `checked_mul()` and correctly rejects overflow, but no oracle comparison has been run against any platform's real clock discipline.

---

## 10. Process management (`privsep.c`, `process.c` · 0 tests)

### Status: **Implemented — unverified against oracle**

| Subsurface | Status | Notes |
|------------|--------|-------|
| `setresuid()` / `setresgid()` | Written | After `setresuid()` there is no `getresuid()` verification |
| Privilege separation architecture | Missing | Requires imsg parent/child framework |
| Chroot/jail support | Missing | `chroot()` not called |
| Capability dropping (Linux) | Missing | No `capng` or `prctl` calls |
| Process title | Missing | `setproctitle()` not wired |
| Daemonization (`fork()`, `setsid()`) | Missing | No double-fork |
| PID file | Missing | No `/var/run/ntpd.pid` |
| Signal handlers | Missing | No `SIGHUP`, `SIGINT`, `SIGTERM`, `SIGALRM` |
| Working directory change | Missing | No `chdir("/")` |

---

## 11. Socket I/O (`io::socket` · 6 tests)

### Implemented — internally tested (loopback)

| Feature | Status | Notes |
|---------|--------|-------|
| IPv4 NTP socket bind | ✓ | Loopback test |
| IPv6 NTP socket bind | ✓ | Loopback test |
| IPv4 send/recv | ✓ | Loopback test |
| IPv6 send/recv | ✓ | Loopback test |
| SO_TIMESTAMP (kernel nanoseconds) | ✓ | Linux kernel timestamp receipt verified |
| SOCK_CLOEXEC | ✓ | Applied |
| `MSG_TRUNC`/`MSG_CTRUNC` rejection | ✓ | Truncation rejected |
| `EINTR` retry | ✓ | `recvmsg()` retries on interrupt |

### NOT implemented / untested

| Subsurface | Risk | Notes |
|------------|------|-------|
| Socket timestamping ancillary parsing | Medium | `recvmsg()` CMSG path structurally correct but untested |
| `decode_sockaddr()` | Fixed in B3 | Invalid pointer cast corrected; no loopback test for both families |
| Hardware timestamping (SOF_TIMESTAMPING) | Low | Linux-specific; not wired |
| Broadcast socket | Low | Mode 5 not implemented |
| Privileged port binding (port 123) | Medium | Current tests bind to arbitrary ports |
| `SO_REUSEADDR` | Low | Not applied |
| `IP_FREEBIND` (Linux) | Low | Not applied |
| `IPV6_V6ONLY` | Low | Not applied |
| `SO_BINDTODEVICE` | Low | Not applied |
| `IP_MTU_DISCOVER` / `IPV6_MTU_DISCOVER` | Low | Not applied |
| `setsockopt(SO_TIMESTAMPNS)` fallback | Low | Only `SO_TIMESTAMP` wired |

---

## 12. CLI argument parsing — full getopt gap analysis

| OpenNTPD form | Rust status | Notes |
|---------------|-------------|-------|
| `-d` | ✓ | |
| `-f <path>` | ✓ | |
| `-f<path>` (attached) | ✗ | Not supported |
| `-n` | ✓ | |
| `-P <name>` | ✓ | |
| `-P<name>` (attached) | ✗ | Not supported |
| `-p <path>` | ✓ | |
| `-p<path>` (attached) | ✗ | Not supported |
| `-s` | ✓ | Deprecated warning |
| `-S` | ✓ | Deprecated warning |
| `-v` | ✓ | Repeatable |
| `-vv` | ✓ | Grouped |
| `-dn` | ✓ | Grouped |
| `-dnv` | ✓ | Grouped |
| `-sn` | ✗ | Not supported; `s` must be last |
| `-Sv` | ✗ | Not supported; `S` must be last |
| `--` terminator | ✗ | Not supported |
| Single `-` (stdin) | ✗ | Not handled |

---

## 13. Number/type parsing — boundary audit

| Type | Format | Range | Upstream validation | Rust status |
|------|--------|-------|-------------------|-------------|
| Weight | Integer | 1–10 | `weight <1-10>` | ✓ `Weight::MIN..=MAX` |
| Stratum | Integer | 1–15 | `stratum 1..15` | ✓ `Stratum::MIN..=MAX` |
| Correction | Integer | ±127,000,000 | `correction ±127000000` | ✓ `CorrectionMicros::MIN..=MAX` |
| RefId | ASCII string | 1–4 chars | `refid "GPS1"` | ✓ `RefId::from_bytes` |
| Routing table | Unsigned int | 0–RT_TABLEID_MAX | Platform-dependent max | ✓ `u32::try_from` (deferred) |
| Address | IPv4/IPv6/hostname | N/A | Numeric via inet_pton | ✓ `core::net::IpAddr::parse` |
| Port | Integer | 0–65535 | Not in grammar | Not exposed (constant 123) |

---

## 14. Docker VM matrix — cross-distro oracle comparison

### Target matrix

| Distribution | Oracle binary | Status |
|-------------|---------------|--------|
| Debian stable | `/usr/sbin/ntpd` (openntpd) | **Not run** |
| Ubuntu LTS | `/usr/sbin/ntpd` (openntpd) | **Not run** |
| Alpine Linux | `/usr/sbin/ntpd` | **Not run** |
| Fedora | `/usr/sbin/ntpd` (ntpsec or openntpd) | **Not run** |
| FreeBSD | `/usr/sbin/ntpd` | **Not run** |

### Harness readiness

| Requirement | Status |
|-------------|--------|
| Self-test without oracle | ✓ 30/30 pass |
| Oracle comparison path | ✓ `--oracle <path>` |
| Oracle SHA-256 pinning | ✓ `--oracle-sha256 <hash>` |
| Self-comparison rejection | ✓ Same binary SHA-256 aborted |
| Self-test evidence receipt | ✓ Committed |
| Oracle receipt format | ⚠ Not yet validated with real oracle |
| Docker integration | ⚠ Not implemented |
| Supported `--oracle-image` flag | ⚠ Documented but not implemented |
| Run-once isolation | ⚠ Pending `target/parity/runs/<ts>-<pid>/` |

### Known binary identity requirements

| Binary | Expected SHA-256 | Source |
|--------|------------------|--------|
| openntpd 7.9p1 (Debian) | Pending | `dpkg -S /usr/sbin/ntpd` |
| openntpd 7.9p1 (source build) | Pending | `sha256sum src/usr.sbin/ntpd/ntpd.c` |

---

## 15. Documentation surface audit

| Document | Status | Notes |
|----------|--------|-------|
| `README.md` | ⚠ Stale | References nonexistent crates and modules |
| crate-level docs (`lib.rs`) | ✓ | Surfaces match generated matrix |
| `port-parity.md` (generated) | ✓ | Auto-updated by `cargo xtask gen` |
| `negative-capabilities.md` (generated) | ✓ | This document |
| `CHANGELOG.md` | Missing | No changelog maintained |
| `CONTRIBUTING.md` | Missing | No contribution guide |
| Oracle build recipe | Missing | No Dockerfile for pinned 7.9p1 build |
| API documentation | ✓ | `rustdoc` standard; `no_std` core |

---

## 16. Security boundary audit

| Concern | Status | Notes |
|---------|--------|-------|
| `no_std` core with `#![deny(unsafe_code)]` | ✓ | No unsafe in protocol/parser/AST |
| Unsafe confined to `io::socket` | ✓ | CMSG/sockaddr casts reviewed |
| `SOCK_CLOEXEC` on all sockets | ✓ | File descriptor leak prevented |
| Privilege dropping scaffolded | ⚠ | `setresuid()`/`setresgid()` written but untested |
| Drift-file symlink safety | ⚠ | Uses `.tmp` extension, no `O_EXCL\|O_NOFOLLOW` |
| Fail-closed exit code | ✓ | 78 for scaffold, 1 for config errors |
| NTP amplification risk | Not applicable | Server mode not implemented |
| NTP replay protection | N/A | Dependent on server mode |
| Timing side channels | Not audited | Cryptographic operations not yet implemented |

---

## 17. RFC compliance surface

| RFC | Title | Status |
|-----|-------|--------|
| RFC 5905 | NTPv4 protocol specification | Wire format only |
| RFC 5906 | NTPv4 Autokey | Not implemented |
| RFC 5907 | NTP MIB objects | Not implemented |
| RFC 5908 | NTPv4 DHCP options | Not implemented |
| RFC 7822 | NTPv4 extension fields | Not implemented |
| RFC 8573 | NTP message checksum | MAC implemented, not required |
| RFC 8915 | NTS (Network Time Security) | Not implemented |
| RFC 9327 | NTP control messages | Parsed but not operational |

---

## 18. Build and deployment gaps

| Concern | Status | Notes |
|---------|--------|-------|
| `.cargo/config.toml` | Missing | Not in repository |
| `.gitignore` | ✓ | Present |
| `.githooks/` | Missing | No githooks for pre-commit |
| Cross-compilation tested | ✗ | x86_64 Linux only |
| `no_std` target verified | ✗ | `thumbv7em-none-eabihf` not tested |
| MSRV (1.81) | ✓ | Declared and applied |
| `-Dwarnings` CI | ✓ | Local only; no CI pipeline |
| `cargo deny` / `audit` | ✗ | No supply-chain checking |
| `cargo xtask no-orig` | ✓ | Ensures no C source in repository |
| Docker images for testing | ✗ | No Dockerfiles or compose |

---

## 19. Code archaeology notes

### Files present in OpenNTPD 7.9p1 with NO Rust counterpart

| C source | Purpose | Rust status |
|----------|---------|-------------|
| `client.c` | Client state machine | **Planned** |
| `server.c` | Responder (mode 4) | **Planned** |
| `control.c` | Control socket imsg | **Planned** |
| `constraint.c` | HTTPS constraint validation | **Planned** |
| `sensors.c` | Sensor framework | **Planned** |
| `sensors_modules/` | Sensor modules (PPS, NMEA, etc.) | **Planned** |
| `dns.c` | async DNS resolution | **Planned** |
| `log.c` | syslog logging | **Planned** |
| `ntp_dns.c` | DNS-to-address resolution | **Planned** |
| `privsep.c` | Privilege separation engine | **Planned** |
| `parse.y` | Full grammar (syntax only) | **Partial** (lexer+parser) |
| `config.c` | Runtime lowering (peer creation) | **Planned** |

### Files with partial Rust coverage

| C source | Rust surface | Coverage |
|----------|-------------|----------|
| `ntp.h` | `ntp` module | Types and wire format only; no poll/select/filter |
| `ntp_msg.c` | `ntp::msg` | Send/receive packet assembly only |
| `util.c` | `util` | Timespec, Frequency only; no clock-select, jitter, dispersion |
| `adjfreq_linux.c` | `io::clock` | Linux `adjtimex` conversion only |
| `socket.c` | `io::socket` | Bind/send/recv only; no privileged bind, no timestamping in daemon loop |
| `ntpd.c` | `daemon` module | `-n` config check only; no event loop, no clock discipline |

---

## 20. Parity evidence status

| Surface | Evidence artifact | Verdict |
|---------|------------------|---------|
| Config check (`-n`) | Self-test receipt (30/30) | **Rust expected behavior confirmed** |
| Config check (`-n`) | Oracle receipt | **Not yet run** |
| All other surfaces | None | **No oracle comparison exists** |

**No surface is labelled `Ported` until `cargo xtask parity` produces a verified evidence artifact against the real OpenNTPD 7.9p1 oracle.**

---

## Deployment boundary

openntpd-rs does **not**:

- discipline a real system clock in production
- run as a privileged daemon
- connect to a running ntpd
- make any production-replacement claim
- replace `ntpd`, `ntpctl`, or `ntp.conf` in any deployment
- handle network time synchronization outside of `-n` config check
- resolve DNS names or perform any async I/O
- validate TLS certificates for constraint URLs
- communicate over the NTP control protocol
- support any NTP mode other than Mode 3 client (not yet wired)
- run on any platform other than x86_64 Linux (untested)
